name: Java CI

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: run basic tests
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        XCMAILR_EMAIL: ${{ secrets.XCMAILR_EMAIL }}
        XCMAILR_PASSWORD: ${{ secrets.XCMAILR_PASSWORD }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_LOGIN: ${{ secrets.EMAIL_LOGIN }}
        EMAIL: ${{ secrets.EMAIL }}
        EMAIL_SERVER: ${{ secrets.EMAIL_SERVER}}
        XCMAILR_TOKEN: ${{ secrets.XCMAILR_TOKEN }}
      run: mvn -B clean test
