name: Deployment

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out source files
      uses: actions/checkout@v2

    - name: Set up JDK 11 and Maven repository
      uses: actions/setup-java@v1
      with:
          java-version: 11
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
    - name: Install GPG key  
      run: echo "${{ secrets.GPG_KEY }}" | gpg --batch --import
    - name: Deploy
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        XCMAILR_EMAIL: ${{ secrets.XCMAILR_EMAIL }}
        XCMAILR_PASSWORD: ${{ secrets.XCMAILR_PASSWORD }}
        SMTP_SERVER_PASSWORD: ${{ secrets.SMTP_SERVER_PASSWORD }}
        SMTP_SERVER_LOGIN: ${{ secrets.SMTP_SERVER_LOGIN }}
        SMTP_SERVER_EMAIL: ${{ secrets.SMTP_SERVER_EMAIL }}
        SMTP_SERVER_HOST: ${{ secrets.SMTP_SERVER_HOST}}
        XCMAILR_TOKEN: ${{ secrets.XCMAILR_TOKEN }}
        run: |
          mvn \
            --no-transfer-progress \
            --batch-mode \
            -Dgpg.passphrase=${{ secrets.GPG_KEY }} \
            clean -P release deploy

