name: Java CI

on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out source files
      uses: actions/checkout@v2
    - name: Set up JDK 11 and Maven repository
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: run basic tests
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-passphrase: GPG_PASSPHRASE
      run: mvn -B clean compile test
